import axios from 'axios';
import * as fsExtra from 'fs-extra';
import { setTimeout } from "timers/promises";

class SendJSONToApi {
    static FILE_PREFIX = './src/json/';

    static async loadInJSONAndCallEndpoint() {
        // Load JSON from a file. Please put json files in 'json' folder
        const jsonFilePath = this.FILE_PREFIX + 'missions.json';

        /* To find your MTC idToken: 
            Log into Embark on web, 
            Look in the network tab, 
            Find 'token' -> Payload, 
            Copy entire 'id-token') 
        */
        const idToken = "";
        const endpointUrl = '';

        try {
            const jsonDataFromFile = await fsExtra.readJson(jsonFilePath);
            const jsonList = (jsonDataFromFile.length === 1) ? [jsonDataFromFile] : jsonDataFromFile;

            const startingIndex = 0;
            const endingIndex = jsonList.length;
            for(let i = startingIndex; i < endingIndex; i++) {
                const postResponse = await this.makePostRequest(jsonList[i], endpointUrl, idToken);
                console.log("Response Retrieved", postResponse);
                
                // Using timeouts to not overwhelm the API
                await setTimeout(500);
            }
        } catch (error) {
            console.log(error);
        }
    }

    static async makePostRequest(jsonData: JSON, endpointUrl: string, idToken: string): Promise<string> {
        console.log("Sending", jsonData);

        // This is a dummy post URL, which will send you back whatever you POST
        // Note that with this Dummy URL an id will be auto generated by the site 
        // (overriding an id if you have one already)
        const dummyApiUrl = 'https://jsonplaceholder.typicode.com/posts'; 
        const dummyAxiosResponse = await axios.post(dummyApiUrl, jsonData);
        return dummyAxiosResponse.data;

        // Update with your actual Construct Lambda Url
        const axiosResponse = await axios.post(endpointUrl, jsonData, {
            headers: {
              'Content-Type': 'application/json',
              'Id': `${idToken}`
            }
        });
        return axiosResponse.data;
    }
}

SendJSONToApi.loadInJSONAndCallEndpoint();
